Refactor with some changes
rancher/Rancher-Plugin-gMSA pull request #31
Opened 2023-12-13 06:04 UTC by aiyengar2

WIP

2024-01-22 20:10 UTC, HarrisonWAffel requested changes
Generally looks good, just some nits here and there

2024-01-22 20:10 UTC, HarrisonWAffel commented on pkg/utils/filesystem.go
> +		// how Microsoft recommends performing DLL Upgrades
(unless this is going to be removed in relation to other certs work)

2024-01-23 20:28 UTC, aiyengar2 commented on pkg/provider/manager/manager.go
> +	UserProvidedCertificates = map[string][]string{
Makes sense, renaming this `Certificates`

2024-01-23 20:36 UTC, HarrisonWAffel commented on pkg/provider/server/server.go
> +		BaseContext: func(net.Listener) context.Context { return ctx },
Overlooked that this was a `http` struct and not a custom type from this project, this makes sense now

2024-01-23 20:37 UTC, aiyengar2 commented on pkg/utils/exec.go
> +		// Powershell was not actually executed
moving comment 👍

2024-01-23 20:37 UTC, aiyengar2 commented on pkg/provider/server/server.go
> +		BaseContext: func(net.Listener) context.Context { return ctx },
BaseContext takes in a function

2024-01-29 17:33 UTC, HarrisonWAffel approved these changes
Nice!

2024-01-29 17:34 UTC, merged